# Generated by Django 2.1.7 on 2019-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190416_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, '未报名'), (2, '已报名')], default=1, verbose_name='状态'),
        ),
    ]
