# Generated by Django 2.0.1 on 2019-04-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_courserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title_in': ['Linux教学部', 'Python教学部']}, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='讲师'),
        ),
    ]
