# Generated by Django 2.0.1 on 2019-04-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190418_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRecord',
            new_name='StudyRecord',
        ),
    ]
